services:
  ext_authz-opa-service-1:
    container_name: opa-service-1
    build:
      context: .
      dockerfile: Dockerfile.opa
    ports:
      - "9002:9002"
      - "8181:8181"  # Expose API port for monitoring and debugging
    volumes:
      - ../commons/certs:/app/tls:ro  # Mount as read-only
      - ./opa-policies:/app/policies:ro
    environment:
      - OPA_ADDR=0.0.0.0:8181
    networks:
      - opa-network
    hostname: opa-service-1
    depends_on:
      usage-tracker:
        condition: service_healthy

  # ext_authz-opa-service-2:
  #   container_name: opa-service-2
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.opa
  #   ports:
  #     - "9003:9002"  # Diferentes portas para o segundo serviço
  #     - "8182:8181"
  #   volumes:
  #     - ../commons/certs:/app/tls:ro
  #     - ./opa-policies:/app/policies:ro
  #   environment:
  #     - OPA_ADDR=0.0.0.0:8181
  #   networks:
  #     - opa-network
  #   hostname: opa-service-2
  #   depends_on:
  #     usage-tracker:
  #       condition: service_healthy

  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - opa-network
    hostname: redis

  opal-server:
    image: permitio/opal-server:latest
    container_name: opal-server
    ports:
      - "7002:7002"
    environment:
      - OPAL_POLICY_REPO_URL=file:///app/policy_repo
      - OPAL_POLICY_REPO_MAIN_BRANCH=master
      - OPAL_POLICY_REPO_POLLING_INTERVAL=60
      - OPAL_DATA_CONFIG_UPDATER_ENABLED=true
      - OPAL_AUTH_MASTER_TOKEN=ZeroTrustDemo2025
      - OPAL_AUTH_PRIVATE_KEY=-----BEGIN RSA PRIVATE KEY-----_MIIJKQIBAAKCAgEA7bREQGMtgKWyNUByhJj8GEc8aThsFQpn1/HBPJQ0klDlbUWV_k/KOTOBCOdDHh+pQaaLZIqgPlAS4lroPIY/3FgdGctXsDtpmlVtsZdJ9nyRYHGiu_3JUx6BypA0aS3Yr5iGHZFLJ4x1EnU72mf+36rpsz/yVupI0kfquYG+bfXS2VopPn_qZbzGECcaIyeevY3ZtlziZ+4rmi13y72IvWUAh7RHxI7udC82XSt58a/ONs0WNqs_B6uIRxQGzPzecoy0grJrxCG8bHKlysrFEHR/2BnI41KC6Ru3RXObeymk4Imf+QWz_ul2luJAPE3aV/s3SqAJCultwKSOVpmedrR77uRk7JWNtqbJEDE4WUynsMWVrrldW_bywuWsqAPMt19qZgdM9GQ5viKjFAa084t9bT5Jt9KCg2wRKrDQsMbxl8QVG0PaGu_RbROH2q5WPeMFj5E2NSodWnFEvyzvMg5joJgziUw/ssxb+3lGiGzoKx2j8oYFXiN_ytd1VIarJiIk1v9V1FnWWq2Ysx1cmVoeECvzfibyZwNLxG/BhXkH/dcPl+eCcyni_PUceYTVNEO57jdkfbS+1f9EecIdEm4io+N2yuaRGWUG19AafWLxlDRRTPRcf2vKO_YRwhY7znm/2zaOdkmgflINcy0B2poc85uOm9WV0uQi1szNUHU3zU+i3LTrsCAwEA_AQKCAgAiXit2EcDc9lgPSfukv0fHrNkHr5A09JWyC7KwMw9szkR1qZdoViwL4mrA_2DZZKOAqfdCeKaVi9dHIfSs944ZKiY++f76LITmuw5KnIClojoUsylfp7apTEH3B_Sv1mCbdtaBROYUWEL/AbM/L0UTCq+Sap77wRD5UkuWObOSS3YKVfZbobc4c/TOww_U5CAX8P/21XQoqa9lMci9zPANziIm/MJZoX7Jjp/yFZyifJQ4qStaiRwUXU5LaSU_E8WH018v/GMHbwdCuMrOyMV4TRfE42l/sIjb8lVrtbzXsFw12MAn7ZKgUfTpe+6q_Fj22owSfpQAH2LudPxdegWGzS6UCRUltLtDEJnfEPmAiiptQxxg+M1I3+ha/Z/fu_qY5WIc5poLz1dBoLFny/eoupTZpGh/YWTedn2JsrWMOXfPZb2MQpnCQPxEjace6q_7jfKVaol8r0UGEtu78znRpUxVEbkyYheuzELmoqjwqr3M9mKvQV4R6bqEk3zZ9dP_XXvfiHqTe8xEeNhhwtv8OEwS8YA6ZQSxBFAsP0lcrNs8Jl2ajIDLiNSsFNLZXrOb_IMBImvE5oCrHu4TBmDkGKV9xHtUVddkWBZNPhMqSbbdl3gDyqC5HqEJGJc9Vzaxz_zpidP/LPraRVxf2p7Rk5138QF5ZPStOQvU3ah9LJiZ89xZEj+QKCAQEA//WMxotf_cKPkgbrVc6BsDZxTPtBHEVpvfiohcqL5BHVQXtPKCvvk+POzc1+8GvEGHlAZcKDK_AwfSn5vd9nx/mLZtnOQmhn90Cp6tgmARms8sVEZeiLrV13YAHwSDqrJDKtKDiqeY_dOVQMiU4XfPUl35qAcRAwsojHiEHJHwompfu7xF6RVXjOlQ4xCFykyc+BL85rNyx_NPJihAbg3h9zu9Sn4y/LGTQOEkItrMsk/7eFUYnQEk5P5XLg4RL8f05U5nwHJE/N_PG7ggbR1gU0SCKhGTiDzE/DunuGfpasQ/aqNEK4932y56WeFXYgdyzCca3pwtxXy_FdzdiZKtMqHtYwKCAQEA7b34rcxJHYUC2T9vpKhf+jxjfxHFzvitC4pTxbrcBPmt_5dxj17mJ3pEnPfu0Tqd38HtHNcNjMkzQwgEFL90BJEoVxL2ySngZwmOellDeMckx_qHZUYwSqxjn+N9uoqdPux+yLH3nCMcMdJ0lNJWJV3leNCh6VPxJFVswJfajDBmio_jRLr6doonijc9vhTsJF22ZbbBD4vpxqfik2Ox2wm3pOSr4EMN5bdJu8Cv7LwhdHZ_6p1SqeAGIQMle5luQGy734iJq8iLiJpe2jrqxqUovjprHbV1s9sl6qTAfH6FJr48_IAzgm8vDNtWSXhT8WYDr3nvPYq6OZ8HT1j+n6YIkyQKCAQEAp1qDeuVxt5JRO8lO_+tTvEU8e1rkTXnNE5rbhO7T3IEUcEYRkXB4qreOZd1wm/26L05IHsC5RJv4cZqNg_02K/grf0n1pFHjeDRdZOGCp8GD5Q+6Eu+jM+0iujFKS8+gSoCf2uaCAAfJ3ae47+_dd+RJqRO52zL8xB7OZ3ar65GVh306XcB/QeVFHQw0XwVD8XetPfa2/1IGBhK9YwR_xunFoBAA3XhIUOhKMwH2Hz6LqG7zykZTN0Tg1GLySfdCBHLQ7Ao4GTPcOyE7xVKa_abpcijCMF1VP2b/0JQncelOJPnIe3cMvTUAnpkY7WtY+tLXJ8DQUMoE00bqhVuwC_NlLNhQKCAQEA0yxsSMxtoZf1aM2NOIALCLY9VrCNuQNwihCryrXpG05AZi22TfdT_fGwIpGkAxuDAi86k+R997D8JK1pGpjYz/m0EGwa46Kb3kpB0XGamhyiEQHQjDvUl_UABRTIKDtZ43ukPla+b2VMdQDQZyTSOkzGOONw/lV+m9x5RjVcfiu72ZAf5tqQIM_FDiN1Z3MkMkU/b+e+YzXPSJL1kh/66moeQoyQExrcrFB7YReN7MVLHizjU+DDruc_FhS6ZahqozUySCL6zqjLMGKWoFe3FQ29PAOeA/yb+U9Oxbbj93FWioxt0bY+iISc_+QcKBSG06Te3y57EHo6YlZc4uFVArAza6QKCAQBUrEBx/jUZQtn26TLOjZ92sHjg_dHIAhvwubrjjgxwx5iAk1Ab75toRXbZtofrRn7r8S7QzG7S+6GmP4dDRxw9tw3xs_hGjH4G8ve6CR0AGDuz2LpX2km+ZazBN97IKWMTOMOkLxXZlzjm0ZVXZ7ml7uKC7B_fQP1/RKMlYxnmzWTNpqW9xy4JcY0DFtM2AYSZXZlwxUeWe+x89IgjSMOgaeXiVUf_BqhA+V8TgmTDuLOMrpfb8DEDuggWMIpHZPnzhH4QVh8uokbDuXMmRRgZOjLz2kQ4_11zKZol31eKDUIZD/OJVqMqgjmUi1cRjigHzk+O/2PUo1+amT2It0Q3lz25f_-----END RSA PRIVATE KEY-----_
      - OPAL_AUTH_PUBLIC_KEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDttERAYy2ApbI1QHKEmPwYRzxpOGwVCmfX8cE8lDSSUOVtRZWT8o5M4EI50MeH6lBpotkiqA+UBLiWug8hj/cWB0Zy1ewO2maVW2xl0n2fJFgcaK7clTHoHKkDRpLdivmIYdkUsnjHUSdTvaZ/7fqumzP/JW6kjSR+q5gb5t9dLZWik+eplvMYQJxojJ569jdm2XOJn7iuaLXfLvYi9ZQCHtEfEju50LzZdK3nxr842zRY2qwHq4hHFAbM/N5yjLSCsmvEIbxscqXKysUQdH/YGcjjUoLpG7dFc5t7KaTgiZ/5BbO6XaW4kA8TdpX+zdKoAkK6W3ApI5WmZ52tHvu5GTslY22pskQMThZTKewxZWuuV1ZvLC5ayoA8y3X2pmB0z0ZDm+IqMUBrTzi31tPkm30oKDbBEqsNCwxvGXxBUbQ9oa5FtE4farlY94wWPkTY1Kh1acUS/LO8yDmOgmDOJTD+yzFv7eUaIbOgrHaPyhgVeI3K13VUhqsmIiTW/1XUWdZarZizHVyZWh4QK/N+JvJnA0vEb8GFeQf91w+X54JzKeI9Rx5hNU0Q7nuN2R9tL7V/0R5wh0SbiKj43bK5pEZZQbX0Bp9YvGUNFFM9Fx/a8o5hHCFjvOeb/bNo52SaB+Ug1zLQHamhzzm46b1ZXS5CLWzM1QdTfNT6LctOuw== abraao@NB-7L9CQ14
      - PORT=7002
      - UVICORN_NUM_WORKERS=2
      - LOG_LEVEL=info
      - OPAL_BROADCAST_URI=redis://redis:6379
    volumes:
      - ./git-repo:/app/policy_repo:ro
    networks:
      - opa-network
    depends_on:
      - redis
    hostname: opal-server

  opal-client-1:
    image: permitio/opal-client:latest
    container_name: opal-client-1
    depends_on:
      - opal-server
      - ext_authz-opa-service-1
    environment:
      - OPAL_SERVER_URL=http://opal-server:7002
      - OPAL_CLIENT_TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NDQyNTcxMzksImV4cCI6MTc3NTc5MzEzOSwiYXVkIjoiaHR0cHM6Ly9hcGkub3BhbC5hYy92MS8iLCJpc3MiOiJodHRwczovL29wYWwuYWMvIiwic3ViIjoiMjdjODE3NjczODRiNGEwNmFiYzZiZWVjMmYzNTM4NjciLCJwZWVyX3R5cGUiOiJkYXRhc291cmNlIn0.gYE5V5A4rYdtNSYTEck2UVWLfKuylhEn2vHxPYHxifQdMPxecxW5F9lZKky0C82a_5oDU7YWsF8_OJ8SSLCug-PJawUz7GqMOkN_p_9vql7yKKZ1LoxZ_AJjCRIKQGaSPw1CHqlEZlTYL9dua0C5m5uaX9eLB7iytMo-5tjxJoHjged0zbuSmdCB9WatAUJQ4DrZsYbDtPhMOAmdUj9fjBeEMxOi6Fcy3rgPC87UoqIZZGXlFq41XwYjLftQ7uO-jsnzyWzZNaLzxoFs_1BWVqTnQErhuhW6ahhsQkvCv2wVSx6m9E8ptX3NczstNmg92A2nmy07OdCKuZGQsPasGZqx7Xs0eQHAp5hCbSTGVzJk42rEsngxbCWMwEo06_Z0VUZeW-cKr0p2xBjOS5v2rgx2WnpRZ6KnaVgYqeonwJUx93rXN56rUgOU1R7uW1ARWJF9Er3-RnzLIvT2g9i9AdiMck8MEe4m1rQymjCY2-qWO_XWPNHQbZLJChqaZu5_JCcZkKWdoiyCeRFflkeusw2-7zfkGiZpH_x9yPBT9uUlhmZQ1z65F1gGLISCljOZNjZ6q_MPqRKd0pZMDXe5ozj9vX9IoLRcw1VThkZEFjoWZbfrmm-UwkOA6xrbyU0nAB1CYJhkz_B2KQLitTaD83D1_sEASXXTqa27uE0I5Lw
      - OPAL_POLICY_PATH=/app/policies/
      - OPAL_INLINE_POLICY_ENABLED=false
      - OPAL_INLINE_OPA_ENABLED=false
      - OPAL_REQUEST_TIMEOUT=15
      - OPAL_CACHE_ENABLED=true
      - OPAL_CACHE_TTL=300
      - LOG_LEVEL=debug
      - OPAL_POLICY_STORE_URL=http://opa-service-1:8181
      - OPAL_POLICY_STORE_AUTH_METHOD=none
      - OPAL_WS_TOKEN=ZeroTrustDemo2025
      # - OPAL_POLICY_STORE_VERIFY_TLS=false
    volumes:
      - ./git-repo:/app/policies:ro
      - ../commons/certs:/app/tls:ro
    networks:
      - opa-network
    hostname: opal-client-1

  # opal-client-2:
  #   image: permitio/opal-client:latest
  #   container_name: opal-client-2
  #   depends_on:
  #     - opal-server
  #     - ext_authz-opa-service-2
  #   environment:
  #     - OPAL_SERVER_URL=http://opal-server:7002
  #     - OPAL_CLIENT_TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NDQyNTcxMzksImV4cCI6MTc3NTc5MzEzOSwiYXVkIjoiaHR0cHM6Ly9hcGkub3BhbC5hYy92MS8iLCJpc3MiOiJodHRwczovL29wYWwuYWMvIiwic3ViIjoiMjdjODE3NjczODRiNGEwNmFiYzZiZWVjMmYzNTM4NjciLCJwZWVyX3R5cGUiOiJkYXRhc291cmNlIn0.gYE5V5A4rYdtNSYTEck2UVWLfKuylhEn2vHxPYHxifQdMPxecxW5F9lZKky0C82a_5oDU7YWsF8_OJ8SSLCug-PJawUz7GqMOkN_p_9vql7yKKZ1LoxZ_AJjCRIKQGaSPw1CHqlEZlTYL9dua0C5m5uaX9eLB7iytMo-5tjxJoHjged0zbuSmdCB9WatAUJQ4DrZsYbDtPhMOAmdUj9fjBeEMxOi6Fcy3rgPC87UoqIZZGXlFq41XwYjLftQ7uO-jsnzyWzZNaLzxoFs_1BWVqTnQErhuhW6ahhsQkvCv2wVSx6m9E8ptX3NczstNmg92A2nmy07OdCKuZGQsPasGZqx7Xs0eQHAp5hCbSTGVzJk42rEsngxbCWMwEo06_Z0VUZeW-cKr0p2xBjOS5v2rgx2WnpRZ6KnaVgYqeonwJUx93rXN56rUgOU1R7uW1ARWJF9Er3-RnzLIvT2g9i9AdiMck8MEe4m1rQymjCY2-qWO_XWPNHQbZLJChqaZu5_JCcZkKWdoiyCeRFflkeusw2-7zfkGiZpH_x9yPBT9uUlhmZQ1z65F1gGLISCljOZNjZ6q_MPqRKd0pZMDXe5ozj9vX9IoLRcw1VThkZEFjoWZbfrmm-UwkOA6xrbyU0nAB1CYJhkz_B2KQLitTaD83D1_sEASXXTqa27uE0I5Lw
  #     - OPAL_POLICY_PATH=/app/policies/
  #     - OPAL_INLINE_POLICY_ENABLED=false
  #     - OPAL_INLINE_OPA_ENABLED=false
  #     - OPAL_REQUEST_TIMEOUT=15
  #     - OPAL_CACHE_ENABLED=true
  #     - OPAL_CACHE_TTL=300
  #     - LOG_LEVEL=debug
  #     - OPAL_POLICY_STORE_URL=http://opa-service-2:8181
  #     - OPAL_POLICY_STORE_AUTH_METHOD=none
  #     - OPAL_WS_TOKEN=ZeroTrustDemo2025
  #     # - OPAL_POLICY_STORE_VERIFY_TLS=false
  #   volumes:
  #     - ./opa-policies:/app/policies:ro
  #     - ../commons/certs:/app/tls:ro
  #   networks:
  #     - opa-network
  #   hostname: opal-client-2

  usage-tracker:
    container_name: usage-tracker
    build:
      context: .
      dockerfile: Dockerfile.usage-tracker
    depends_on:
      - opal-server
    ports:
      - "8080:8080"  # Expose the webhook port
    environment:
      - OPAL_SERVER_URL=http://opal-server:7002
      - OPAL_AUTH_TOKEN=ZeroTrustDemo2025
      - OPAL_WS_TOKEN=ZeroTrustDemo2025
      - LOG_COLLECTION_METHOD=webhook  # Only use webhook mode
      - WEBHOOK_PORT=8080
      - UPDATE_INTERVAL=5
      - TIME_WINDOW=60
      - LOG_LEVEL=debug  # Change to debug for more verbose logging
    networks:
      - opa-network
    restart: unless-stopped
    hostname: usage-tracker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

  # Serviço Envoy
  envoy:
    image: envoyproxy/envoy:v1.22.0
    container_name: envoy
    ports:
      - "8001:8001"
    volumes:
      - ./envoy:/etc/envoy
      - ../commons/certs:/etc/envoy/certs:ro
    networks:
      - opa-network
    depends_on:
      - ext_authz-opa-service-1
      # - ext_authz-opa-service-2
      - api-service
    hostname: envoy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/ready"]
      interval: 5s
      timeout: 2s
      retries: 3
docker 
  # Serviço da API real
  api-service:
    build:
      context: ../commons/service
      dockerfile: Dockerfile
    container_name: api-service
    networks:
      opa-network:
        aliases:
          - service.zt.local
    hostname: service.zt.local
    ports:
      - "8889:8888"
    environment:
      - DB_PATH=/app/items.db
      - PORT=8888
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8888/items"]
      interval: 5s
      timeout: 2s
      retries: 3

volumes:
  opa-logs-1:
  opa-logs-2:

networks:
  opa-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16